# Generated by Django 3.1.1 on 2020-10-02 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybill',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='mess',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
