# Generated by Django 3.1.1 on 2020-10-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_mess_mess_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rollno',
            new_name='student_id',
        ),
    ]
